---
abstract: 'Generate data files for use with Open Flash Chart'
author:
  - 'Dave Rolsky <autarch@urth.org>'
build_requires:
  Test::More: 0.88
  Test::Requires: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300006, CPAN::Meta::Converter version 2.113640'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Chart-OFC
requires:
  Graphics::ColorNames: 0
  List::MoreUtils: 0
  Moose: 0.56
  MooseX::StrictConstructor: 0.07
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Chloro
  repository: git://git.urth.org/Chloro.git
version: 0.11
